# Generated by Django 4.1.7 on 2023-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
